In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
#Creating a One-Dimensional Array
import numpy as np

numbers = np.array([10,20,30,40,50])

print(numbers)

[10 20 30 40 50]


In [ ]:
#Creating a Two-Dimensional Array

marks = np.array([
    [85,90,88],
    [75,80,78]
])

print(marks)

[[85 90 88]
 [75 80 78]]


In [ ]:
# Creating Three-Dimensional Array
import numpy as np

data = np.array([
[
[1,2],
[3,4]
],
[
[5,6],
[7,8]
]
])

print(data)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Special Array Creation Functions

In [ ]:
# zeros()
import numpy as np

arr = np.zeros((3,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ones()
arr = np.ones((2,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# empty()
arr = np.empty((2,3))

print(arr)

[[5.09659479e-315 0.00000000e+000 0.00000000e+000]
 [1.25990589e-300 2.49208272e-306 4.60024523e-320]]


In [ ]:
# arange()
arr = np.arange(1,11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.arange(5,26,5)

print(arr)

[ 5 10 15 20 25]


In [ ]:
# linespace()
arr = np.linspace(1,10,5)

print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# indentity()
I = np.identity(4)

print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.array([
[10,20,30],
[40,50,60]
])
#print(arr)
#print(arr.ndim)
#print(arr.shape)
#print(arr.size)
#print(arr.dtype)
print(arr.itemsize)

8


In [ ]:
# One-Dimensional Indexing
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[1])    # Second element
print(numbers[3])    # Fourth element
print(numbers[-2])   # Second last element

20
40
40


In [ ]:
# Two-Dimensional Indexing
arr = np.array([
[10,20,30],
[40,50,60],
[70,80,90]
])

print(arr[0,2])
print(arr[2,1])

30
80


In [ ]:
# Array Slicing :

In [ ]:
#1D Array
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])      # [20 30 40]
print(arr[:3])       # [10 20 30]
print(arr[2:])       # [30 40 50 60]
print(arr[::2])      # [10 30 50]
print(arr[::-1])     # [60 50 40 30 20 10]

[20 30 40]
[10 20 30]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
# 2D Array :
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# First two rows
#print(arr[0:2]) # array[start_row:end_row]

# First row
#print(arr[0, :])

# Second column
#print(arr[:, 1])

# First two rows and first two columns
#print(arr[0:2, 0:2])

In [ ]:
# 3D Array
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr[:, 0, :])

[[1 2]
 [5 6]]


In [ ]:
arr = np.array([10, 20, 30, 40])

slice_arr = arr[1:3]
slice_arr[0] = 99

print(arr)

[10 99 30 40]


In [ ]:
# Arithmetic Operations

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


In [ ]:
print(a - b)

[ 9 18 27]


In [ ]:
print(a * b)

[10 40 90]


In [ ]:
print(a / b)

[10. 10. 10.]


In [ ]:
print(a // b)

[10 10 10]


In [ ]:
np.array([5]) / np.array([2])

array([2.5])

In [ ]:
np.array([5]) // np.array([2])

array([2])

In [ ]:
print(a % b)

[0 0 0]


In [ ]:
a = 10

In [ ]:
print(a ** 2)

100


In [ ]:
a=10
b=20
print(a > b)

False


In [ ]:
a == b
a != b
a < b
a <= b
a >= b

False

In [ ]:
a=100
np.sqrt(a)

np.float64(10.0)

In [ ]:
np.square(a)

np.int64(10000)

In [ ]:
b=2
np.exp(b)

np.float64(7.38905609893065)

e = 2.718281828

In [ ]:
# Logarithm
np.log(85)

np.float64(4.442651256490317)

In [ ]:
# Absolute Value
arr = np.array([-5, -10, 20])
print(np.abs(arr))

[ 5 10 20]


In [ ]:
# Aggregate Functions
#These calculate values for the whole array.
arr = np.array([10,20,30,40])
np.sum(arr)

np.int64(100)

In [ ]:
np.mean(arr)

np.float64(25.0)

In [ ]:
np.max(arr)

np.int64(40)

In [ ]:
np.min(arr)

np.int64(10)

In [ ]:
np.std(arr)

np.float64(11.180339887498949)

In [ ]:
# Operations with a Scalar
a = np.array([1,2,3])

print(a + 5)

[6 7 8]


In [ ]:
print(a * 10)

[10 20 30]


In [ ]:
# Broadcasting
a = np.array([[1,2,3],
              [4,5,6]])
print(a+10)

[[11 12 13]
 [14 15 16]]


In [ ]:
# np.sum()
arr = np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [ ]:
#np.min()
arr = np.array([5,10,2,8])
print(np.min(arr))

2


In [ ]:
print(np.max(arr))

10


In [ ]:
# np.sqrt()
arr = np.array([4, 9, 16])
print(np.sqrt(arr))

[2. 3. 4.]


In [ ]:
arr = np.array([1, 2, 3])
print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
arr = np.array([1, 10, 100])
print(np.log(arr))

[0.         2.30258509 4.60517019]


In [ ]:
#np.mean()
arr = np.array([10, 20, 30, 40])

print(np.mean(arr))

25.0


In [ ]:
#np.median()
arr = np.array([10, 20, 30, 40, 50])

print(np.median(arr))

30.0


In [ ]:
# np.std() (Standard Deviation)
arr = np.array([10, 20, 30, 40])

print(np.std(arr))

11.180339887498949


In [ ]:
#  np.var() (Variance)
arr = np.array([10, 20, 30, 40])

print(np.var(arr))

125.0


In [ ]:
# np.min()
arr = np.array([12, 5, 18, 3])

print(np.min(arr))

3


In [ ]:
# np.max()
print(np.max(arr))

18


In [ ]:
# np.sum()
print(np.sum(arr))

38


In [ ]:
# np.percentile()
arr = np.array([10, 20, 30, 40, 50])

print(np.percentile(arr, 50))

30.0


In [ ]:
# np.cumsum() (Cumulative Sum)
arr = np.array([1, 2, 3, 4])

print(np.cumsum(arr))

[ 1  3  6 10]


In [ ]:
# Example 1: Single Random Number

print(np.random.rand())

0.2371788606129659


In [ ]:
# Example 2: 2×3 Random Array
arr = np.random.rand(2, 3)
print(arr)

[[0.39748338 0.12667425 0.83748729]
 [0.62505964 0.82428547 0.40264014]]


In [ ]:
# np.random.randint()

In [ ]:
print(np.random.randint(1, 10))

8


In [ ]:
arr = np.random.randint(1, 100, size=5)
print(arr)

[81 66 12 97 70]


In [ ]:
arr = np.random.randint(1, 20, size=(2,3))
print(arr)

[[ 3  8 11]
 [ 1  7  7]]


In [ ]:
# np.random.choice()
colors = ["Red", "Blue", "Green", "Yellow"]

print(np.random.choice(colors))

Blue


In [ ]:
numbers = [10, 20, 30, 40, 50]

print(np.random.choice(numbers, size=3))

[40 50 50]


In [ ]:
# np.random.seed()

np.random.seed(10)

print(np.random.randint(1, 10))
print(np.random.randint(1, 10))

5
1


In [ ]:
# np.random.shuffle()
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)

print(arr)

[3 5 1 4 2]


In [ ]:
# np.random.normal()
arr = np.random.normal(loc=50, scale=10, size=5)

print(arr)

[46.23697447 50.66032678 39.8293635  59.07624223 43.17876151]


In [ ]:
# Other Useful Random Functions

In [ ]:
# np.random.random()

# Generates random floats between 0 and 1.
print(np.random.random(5))

[0.68381843 0.81660184 0.33607158 0.89081653 0.19812181]


In [ ]:
# np.random.randn()
# Generates random numbers from the standard normal distribution (mean = 0, standard deviation = 1).
print(np.random.randn(5))

[-0.46121833  0.31085074  1.72937588 -0.24066194 -1.02735202]


In [ ]:
#np.random.uniform()
#Generates random numbers from a uniform distribution.
print(np.random.uniform(10, 20, 5))

[17.78728808 15.83901366 11.82631436 18.26082248 11.05401833]


In [ ]:
# Creating a Matrix:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# Matrix Addition

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = A + B

print(C)

[[ 6  8]
 [10 12]]


In [ ]:
C = A - B

print(C)

[[-4 -4]
 [-4 -4]]


In [ ]:
C = np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


In [ ]:
C = A @ B

print(C)

[[19 22]
 [43 50]]


In [ ]:
# Transpose of Matrix
A = np.array([[1,2],
              [3,4]])

print(A.T)

[[1 3]
 [2 4]]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Sum =", np.sum(arr))
print("Average =", np.mean(arr))
print("Maximum =", np.max(arr))
print("Minimum =", np.min(arr))

Array: [10 20 30 40 50]
Sum = 150
Average = 30.0
Maximum = 50
Minimum = 10


In [ ]:
import numpy as np

arr = np.array([12, 15, 18, 21, 24, 27])

even = arr[arr % 2 == 0]

print(even)

[12 18 24]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

square = arr ** 2

print(square)

[ 1  4  9 16 25]


In [ ]:
import numpy as np

arr = np.arange(1, 13)

matrix = arr.reshape(3,4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = A + B

print(C)

[[ 6  8]
 [10 12]]


In [ ]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.matmul(A,B))
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

arr = np.random.randint(1, 50, size=10)

print(arr)

[29 30 48 29  4 48 15  1 36 41]


In [ ]:
import numpy as np

arr = np.array([40,10,50,20,30])

print(np.sort(arr))

[10 20 30 40 50]


In [ ]:
import numpy as np

arr = np.array([2,4,6,8,10])

print(np.std(arr))

2.8284271247461903
